version: 2.1
jobs:
#start of builds as a default action
  build:
    working_directory: ~/PythonOOD
    docker:
      - image: cimg/python:3.9.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Testing" #runs some command
#end of builds as a default action
