version: 2.1
jobs:
#start of builds as a default action
  build:
    docker:
      username: mydockerhub-user
      password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: #runs some command
          echo "Sup friendos"
#end of builds as a default action
