version: 2.1
jobs:
#start of builds as a default action
  build:
    working_directory: ~/PythonOOD
#Used to define the local environment that py is run in    
    environment:
      PIPENV_VENV_IN_PROJECT: false
#Container for python
    docker:
      - image: cimg/python:3.9.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
#The actual pipeline
    steps:
      - checkout
      #Creates the environment needed to run the code
      - run:
          name: Build venv
          command: |
            python3 -m venv ~/PythonOOD/_venv
            source _venv/bin/activate
      #Runs the code to make sure it compiles
      - run:
          name: run main
          command: |
            python3 src
##Future tests will be made in a seperate folder, using pytest