version: 2.1
jobs:
#start of builds as a default action
  build:
    working_directory: ~/PythonOOD
#Used to define the local environment that py is run in    
    environment:
      PIPENV_VENV_IN_PROJECT: false
#Container for python
    docker:
      - image: cimg/python:3.9.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
#The actual pipeline
    steps:
      - checkout
      - run: 
        command: |
          venv run python main.py